config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users
  resources :posts
  resources :students
  
  root 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :image, :age, :gender, :company, :skills, :mobile, :email, :address, :pin, :state, :country, :bio)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]



  #def show
  #end

  #def new
  #  @profile = Profile.new
  #end

  def edit
     @profile = current_user.profile
  end

  def update
      @profile = current_user.profile
    respond_to do |format|
      if @profile.update profile_params
        format.html { redirect_to edit_profile_path, notice: "Profile updated!" }
        format.json { render :edit, status: :ok, location: @profile }
      else
        format.html { redirect_to edit_profile_path, flash: { error: "Profile could not be updated!" } }
        format.json { render json: @profile.errors.messages, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :gender, :phone, :address, :pin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_footer.html.erb
<div class="fixed-bottom">
  <footer>
    <p>G VINAY KUMAR<br>
    <a href="mailto:vinay@example.com">vinay@example.com</a></p>
  </footer>
</div>

app/views/layouts/_header.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<!-- Navigation -->
<div class="fixed-top">
  <header class="topbar">
      <div class="container">
        <div class="row">
          <!-- social icon-->
          <div class="col-sm-12">
            <ul class="social-network">
              <li><a class="waves-effect waves-dark" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="waves-effect waves-dark" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="waves-effect waves-dark" href="#"><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>

        </div>
      </div>
  </header>
  <header>
      <nav class="navbar navbar-expand-lg navbar-dark mx-background-top-linear">
        <div class="container">
          <a class="navbar-brand" rel="nofollow" target="_blank" href="http://scadonsak.com/7bF" style="text-transform: uppercase;"> DEMO APPLICATION</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">

            <ul class="navbar-nav ml-auto">

              <li class="nav-item active">
                <a class="nav-link" href="http://localhost:3000/">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="http://localhost:3000/profiles">Profile
                  <span class="sr-only">(current)</span>
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
            
              <li class="nav-item">
                <% if user_signed_in? %>
                <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
                <% end %>
              </li>

            </ul>
          </div>
        </div>
      </nav>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= render 'layouts/header' %>
    <%= render 'layouts/footer' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <%= form_with(model: @post, class: "shadow p-3 mb-3 bg-info rounded", local: true, html: { multipart: true }) do |f| %>
        


        <div class="container">
        <% if @post.errors.any? %>
          <h2>The following errors prevented the post from being saved</h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        <% end %>

        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "enter name" %>
            </div>
        </div>

         <div class="form-group row">
            <%= f.file_field :image %>
        </div>

        <div class="form-group row">
          <%= f.label :age, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.number_field :age, class: "form-control shadow rounded", placeholder: "enter age" %>
            </div>
        </div>

        <div class="form-group row">
          <%= f.label :gender, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :gender, class: "form-control shadow rounded", placeholder: "enter male or female or other" %>
            </div>
        </div>

        <div class="form-group row">
          <%= f.label :company, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :company, class: "form-control shadow rounded", placeholder: "enter company" %>
            </div>
        </div>

        
        <div class="form-group row">
          <%= f.label :skills, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :skills, class: "form-control shadow rounded", placeholder: "write your skills" %>
            </div>
        </div>

        <div class="form-group row">
          <%= f.label :mobile, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.number_field :mobile, class: "form-control shadow rounded", placeholder: "enter mobile" %>
            </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :email, class: "form-control shadow rounded", placeholder: "enter email" %>
            </div>
        </div>

        <div class="form-group row">
          <%= f.label :address, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
              <%= f.text_area :address, rows: 10, class: "form-control shadow rounded", placeholder: "Current address" %>
            </div>
        </div>

        <div class="form-group row">
          <%= f.label :pin, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :pin, class: "form-control shadow rounded", placeholder: "enter pin" %>
            </div>
        </div>

        <div class="form-group row">
          <%= f.label :state, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :state, class: "form-control shadow rounded" %>
            </div>
        </div>

        <div class="form-group row">
          <%= f.label :country, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :country, class: "form-control shadow rounded" %>
            </div>
        </div>

        <div class="form-group row">
          <%= f.label :bio, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
              <%= f.text_area :bio, rows: 10, class: "form-control shadow rounded", placeholder: "Biodata" %>
            </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <%= link_to '[ Cancel and return to posts listing ]', posts_path, class: "text-info" %>
  </div>
</div>

app/views/posts/edit.html.erb
<body style="background-color:navajowhite;">

	<div id="page-content">
	  <h1 class="text-center mt-4">Edit article</h1>
	  <%= render 'form' %>
	</div>

</body>

app/views/posts/index.html.erb
<div id="page-content">
  <h5>
    <%= link_to 'click here to see total students list', controller: 'students' %>
  </h5>
  <h3 class="text-center mt-4">Listing all posts</h3>

<body style="background-color:whitesmoke;">

<p id="notice"><%= notice %></p>

<table>
  <tbody>
      <div class="container">
    <% @posts.each do |post| %>
      <div class="row justify-content-md-center">
        <div class="col-16 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              Demo Application
            </div>
            <div class="card-body">
              <h5 class="card-string"><%= link_to post.name, post_path(post), class: "text-success" %></h5>
              <h5 class="card-integer"><%= link_to post.age, post_path(post), class: "text-success" %></h5>
              <h5 class="card-string"><%= link_to post.company, post_path(post), class: "text-success" %></h5>
              
              <h5 class="card-string"><%= link_to post.email, post_path(post), class: "text-success" %></h5>
              <%= link_to "Full Profile", post_path(post), class: "btn btn-outline-success" %>
              <%= link_to "Edit", edit_post_path(post), class: "btn btn-outline-info" %>
              <%= link_to "Delete", post_path(post), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
              <p>
                <%= link_to 'Create new Post', new_post_path %>
              </p>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(post.created_at) %> ago, 
              edited <%= time_ago_in_words(post.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div> 
  </tbody>
</table>

</body>
 

app/views/posts/new.html.erb
<body style="background-color:ghostwhite;">

	<div id="page-content">
	  <h1 class="text-center mt-4">Create a new Post</h1>
	  <%= render 'form' %>
	</div>

</body>

app/views/posts/show.html.erb
<body style="background-color:navajowhite;">
  <div id="page-content">
    <h2 class="text-center mt-4"><%= @post.name %></h2>
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              by Demo Application
            </div>
            <div class="card-body">
              <div class="card-text text-center"><%= image_tag @post.image.url(:thumb) %></div>
              <div class="card-text text-left"><%= simple_format(@post.gender) %></div>
              <div class="card-text text-left"><%= simple_format(@post.company) %></div>
              <div class="card-text text-left"><%= simple_format(@post.skills) %></div>

              <div class="card-text text-left"><%= simple_format(@post.email) %></div>
              <div class="card-text text-left"><%= simple_format(@post.address) %></div>
              
              <div class="card-text text-left"><%= simple_format(@post.state) %></div>
              <div class="card-text text-left"><%= simple_format(@post.country) %></div>
              <div class="card-text text-left"><%= simple_format(@post.bio) %></div>
              <%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-info" %>
              <%= link_to "Delete", post_path(@post), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(@post.created_at) %> ago, 
              edited <%= time_ago_in_words(@post.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>

</body>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.number_field :mobile %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.city %></td>
        <td><%= profile.mobile %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @profile.city %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @profile.mobile %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :pin %>
    <%= form.number_field :pin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Pin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.gender %></td>
        <td><%= student.phone %></td>
        <td><%= student.address %></td>
        <td><%= student.pin %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>
<br>
<%= link_to 'Back', posts_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @student.gender %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <strong>Pin:</strong>
  <%= @student.pin %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>